### ISSUE TITLE
Mutable StarlarkValue?

### ISSUE THREAD

**Issue by raphaelhetzel** [facebook/starlark-rust#126]
Hi,

is there any documentation on how to implement mutable methods/attributes on a `StarlarkValue`?

The documentation suggests that if one wants a mutable value, one has to implement `ComplexValue`, however, that trait does not define mutable versions of the methods in `StarklarkValue`.

I could just use a RefCell in the struct and prevent modification that after freezing the value but that didn't seem right.

Raphael

**Comment by ndmitchell** [comment]
A RefCell is exactly the right way to do it. For example, Dict is implemented using a RefCell here - https://github.com/facebook/starlark-rust/blob/d6cc74db4462428a2808693166118a10848bb605/starlark/src/values/types/dict/value.rs#L123. Note that Dict is quite complex because of how fundamental they are to the language, so a normal mutable type with RefCell shouldn't be as complex.

**Comment by ndmitchell** [comment]
Added that as a comment in 68ce5bc8ac802c8f2f0c4d20b3d194a6a992a965.

**Comment by raphaelhetzel** [comment]
Thanks, then my approach wasn't wrong.
I was confused by this comment: https://github.com/facebook/starlark-rust/blob/68ce5bc8ac802c8f2f0c4d20b3d194a6a992a965/starlark/src/values/traits.rs#L200.

**Comment by ndmitchell** [comment]
Thanks - that used to be the case, but stopped being so a while ago. I've updated the docs to:

```
/// * A type is not [`Send`] and [`Sync`], typically because it contains
///   interior mutability such as a [`RefCell`](std::cell::RefCell).
```
